### ISSUE TITLE
logo 

### ISSUE THREAD

**Issue by thebalazs** [THE-SOURCE-CODE-AGENCY/Candidate-Lookup-by-CODE#12]
1. legyen nagyobb
2. menjen jobbra 

![Screenshot 2022-09-12 at 18 47 51](https://user-images.githubusercontent.com/33448047/189714481-9983e554-103a-4535-9e05-72055c7b79f7.png)

**Comment by GuBee33** [comment]
a 25px az a platform ikonokra vonatkozik. azt is növeljem?

**Comment by thebalazs** [comment]
jaaa, bocs, azt hittem, az is a logóhoz tartozik. csak a logót akartam növelni!!
