### ISSUE TITLE
CODΞ

### ISSUE THREAD

**Issue by thebalazs** [THE-SOURCE-CODE-AGENCY/Candidate-Lookup-by-CODE#13]
ezt kérlek, javítsd mindkét helyen 

![Screenshot 2022-09-12 at 18 48 49](https://user-images.githubusercontent.com/33448047/189714685-0403eb11-71c6-433a-8796-c5905c34837f.png)

![Screenshot 2022-09-12 at 18 19 09](https://user-images.githubusercontent.com/33448047/189714712-48d96bcd-8437-4eb4-9812-ad9792710d39.png)

**Comment by GuBee33** [comment]
#11 duplikált issue
