### ISSUE TITLE
Search és Save&Search

### ISSUE THREAD

**Issue by thebalazs** [THE-SOURCE-CODE-AGENCY/Candidate-Lookup-by-CODE#20]
mi lenne, ha lenne egy **SEARCH** gomb és egy **SAVE & SEARCH**

tehát a csak **SAVE** nem kellene 

![Screenshot 2022-09-12 at 19 17 43](https://user-images.githubusercontent.com/33448047/189716490-116e8a0e-5e7d-4a26-b701-fafc95d7d5bf.png)

**Comment by GuBee33** [comment]
Ha nagyon szeretnéd meg tudom csinálni, csak kicsit macerás... mert akkor kell egy tök új function-t írni hozzá.

a különbség az hogy save után nem zárja be az ablakot, save&search után pedig bezárja és egyből keres is
