### ISSUE TITLE
felesleges Delete szöveg (töröld ki lszi!) 

### ISSUE THREAD

**Issue by thebalazs** [THE-SOURCE-CODE-AGENCY/Candidate-Lookup-by-CODE#26]
![Screenshot 2022-09-13 at 17 54 44](https://user-images.githubusercontent.com/33448047/189950185-b9b90c6e-ae6d-4312-92f8-dad3934c8bd6.png)

**Comment by GuBee33** [comment]
szerintem ez nem releváns. az ott csak akkor jelenik meg ha sikeresen töröltél valamit. utána el is tűnik 0,75 sec múlva.

kérlek erősítsd majd meg hogy így van

**Comment by thebalazs** [comment]
sajnos, nem. most a felugró ablakról beszélünk, és ott alapból ott van. (az extension gombnál úgy működik, ahogy írtad, de ez a jobb gombos panel)

**Comment by GuBee33** [comment]
rájöttem hogy tördelési hiba, az a köv sorba kellett volna hogy legyen.
javítom
