### ISSUE TITLE
felugró ablak (jobb gomb) pici restructure 

### ISSUE THREAD

**Issue by thebalazs** [THE-SOURCE-CODE-AGENCY/Candidate-Lookup-by-CODE#29]
Tomi, "aludtam" rá egyet, és sztem ez a struktúra jobb lenne. remélem, nem hatalmas meló megcsinálni? 

process-szinten

- ha kiválasztanak platformokat, SEARCH keres rajta instans
- ha el akarják menteni a platform választást, akkor arra is van opció 
- itt lszi írják át a szöveget, erre: **Save your selection. Name it:** 
- Itt csak SAVE-elni tudnak, de a SAVE után a fenti panelban egyből látszódni fog a SAVED SEARCH OPCIÓ (ahogy most van) és ott tudnak keresni rá 
- alatta DELETE (ahogy most) 

és a SEARCH gomb megnyomása után mindig autoclose az ablakon 

mennyire extra meló? ha ez megvan, akkor sztem megvagyunk!!! 

![final 1](https://user-images.githubusercontent.com/33448047/189967464-be8d96e4-5921-4869-a874-e4f45e247946.png)

**Comment by GuBee33** [comment]
Hasonló volt eredetileg.

Megnézem. 
Illetve ez meg lehet megoldja majd a nyitott ablakot

chrome.tabs.query({}, function(tabs) {
  var doFlag = true;
  for (var i=tabs.length-1; i>=0; i--) {
    if (tabs[i].url === "chrome-extension://EXTENSION_ID/feedback-panel.html") {
      //your popup is alive
      doFlag = false;
      chrome.tabs.update(tabs[i].id, {active: true}); //focus it
      break;
    }
  }
  if (doFlag) { //it didn't found anything, so create it
    window.open('feedback-panel.html', 'Feedback', 'width=935, height=675');
  }
});
