### ISSUE TITLE
(design) sortörés kérés az Extension gombnál 

### ISSUE THREAD

**Issue by thebalazs** [THE-SOURCE-CODE-AGENCY/Candidate-Lookup-by-CODE#31]
a nyilakhoz kéne sortörés, hogy ugyanaz a look-n-feel legyen az Extension gombnál, int a felugró ablak esetében 

![Screenshot 2022-09-14 at 9 03 34](https://user-images.githubusercontent.com/33448047/190084522-2173f521-cd3b-41b9-a11a-d4c97fa0b918.png)

**Comment by GuBee33** [comment]
implemented. 
köv releasben benne lesz
