### ISSUE TITLE
(design) az Extension gombnál a SAVE

### ISSUE THREAD

**Issue by thebalazs** [THE-SOURCE-CODE-AGENCY/Candidate-Lookup-by-CODE#32]
az Extension gombnál a SAVE... legyen ugyanabban a designban, mint a felugrónál

Szöveg (_Save your selection, name it:_) --> Text box --> Gomb 

![Screenshot 2022-09-14 at 9 06 28](https://user-images.githubusercontent.com/33448047/190085073-1923f29b-567d-4830-bbec-4894dc773283.png)

**Comment by GuBee33** [comment]
implemented. 
köv releasben benne lesz
