### ISSUE TITLE
(design) a CODE a jobb gombnál még nem jó

### ISSUE THREAD

**Issue by thebalazs** [THE-SOURCE-CODE-AGENCY/Candidate-Lookup-by-CODE#35]
de MINDENHOL MÁSHOL már szuper!!! 

![Screenshot 2022-09-14 at 8 56 38](https://user-images.githubusercontent.com/33448047/190085591-57f20d9f-c01c-4260-94aa-796950523194.png)

**Comment by GuBee33** [comment]
nyomsz egy refresht az extensionre és jó lesz. ez azért van mert ez egy dev módban lévő verzió, elvileg a publikáltnál nem így lesz. de azért még utána nézek

**Comment by thebalazs** [comment]
sajnos még mindig nem jó nekem - leszedtem a legújabb verziót (main 8) 


<img width="488" alt="Screenshot 2022-09-14 at 13 52 06" src="https://user-images.githubusercontent.com/33448047/190149420-66751cec-7cd0-4269-9fa8-648db3c6b668.png">
