### ISSUE TITLE
(functionality) Instagram search link 

### ISSUE THREAD

**Issue by thebalazs** [THE-SOURCE-CODE-AGENCY/Candidate-Lookup-by-CODE#36]
Megtennéd, kérlek, hogy az Instagram search linket így módosítod? ez 

https://www.google.com/search?q=site%3Ainstagram.com+"full name"+-intitle%3Ahashtag+-site%3Ainstagram.com%2Fp%2F*+-site%3Ainstagram.com%2F*%2Fp%2F

**Comment by GuBee33** [comment]
implemented. 
köv releasben benne lesz
