### ISSUE TITLE
(functionality) egyéb platformok

### ISSUE THREAD

**Issue by thebalazs** [THE-SOURCE-CODE-AGENCY/Candidate-Lookup-by-CODE#37]
korábban írtuk még sztem a másik repo-ban, hogy 3 egyéb platformot bevihetnénk. nem találtam meg a closed issue-k között, de te tuti megtalálod

ezek voltak: 

- Medium
- YouTube
- Nickname search (Vince javaslata) 

ez megoldható még?

**Comment by GuBee33** [comment]
szia,

azért nincs closed-ban mert még open :) 
https://github.com/GuBee33/Code---chrome-extension/issues/26

és most látam csak hogy végül ezt kitöltötétek. mindjárt megnézem és implementálom

**Comment by GuBee33** [comment]
implemented. 
köv releasben benne lesz
