### ISSUE TITLE
néha kétszer ugrik fel az Option ablak 

### ISSUE THREAD

**Issue by thebalazs** [THE-SOURCE-CODE-AGENCY/Candidate-Lookup-by-CODE#4]
![Screenshot 2022-09-12 at 7 23 00](https://user-images.githubusercontent.com/33448047/189579420-23fb215f-b937-4f95-b9f0-8078ff90b098.png)

**Comment by thebalazs** [comment]
úgy néz ki, csak akkor, ha egy korábban felugrott ablak MÉG nyitva van, akkor minden új nyitás esetben duplán ugrik fel

**Comment by thebalazs** [comment]
update :) annyiszor ugrik fel, ahányszor már nyitva van +1 

tehát ha már háromszor nyitva van, akkor következő esetben már négyszer nyitja meg az options-t

**Comment by thebalazs** [comment]
és itt, a duplikált ablakoknál néha lefagy és nem működnek a Search gombok

**Comment by katakata-lab** [comment]
Tomi, ha most nem csuktam be az előző ablakot, megint duplán ugrik fel:

<img width="959" alt="image" src="https://user-images.githubusercontent.com/67629049/189889877-605eab77-8bf2-4d13-b838-abef90547a8c.png">
