### ISSUE TITLE
jobb gomb E betű 

### ISSUE THREAD

**Issue by thebalazs** [THE-SOURCE-CODE-AGENCY/Candidate-Lookup-by-CODE#42]
hahó Tomi - KÉSZ A TOOL! 

megtennéd, kérlek, hogy a jobb gomb feliratnál átírod az E betűt rendesre? 

az az egy, ami nem jön be soha. 

köszönöm!

<img width="474" alt="Screenshot 2022-09-15 at 9 24 21" src="https://user-images.githubusercontent.com/33448047/190341241-9b1a4ee0-797f-477d-8cfb-013ca8489538.png">

**Comment by GuBee33** [comment]
Ha frissíted utána se? Nálam jó és így nem tudom hogy kellene átírni. Megvárhatjuk vele hogy ha rendesen települ az extension akkor is fennáll e a probléma?

**Comment by thebalazs** [comment]
ha gondolod, várjuk. törlöm, frissítem, újrarakom, bármi... még mindig CODIZ ;)

**Comment by GuBee33** [comment]
lehet hogy platform függő (volt) de most fogtam és hard coded (ASCII-ban megadva) beírtam neki. Így már jónak kell lennie
