### ISSUE TITLE
Edge verzió

### ISSUE THREAD

**Issue by thebalazs** [THE-SOURCE-CODE-AGENCY/Candidate-Lookup-by-CODE#44]

**Comment by GuBee33** [comment]
Ezt nézzük meg

https://support.microsoft.com/en-us/microsoft-edge/add-turn-off-or-remove-extensions-in-microsoft-edge-9c0ec68c-2fbc-2f2c-9ff0-bdc76f46b026

**Comment by GuBee33** [comment]
kirpóbáltam, működik.
