### ISSUE TITLE
Option-ben Platform selection 

### ISSUE THREAD

**Issue by thebalazs** [THE-SOURCE-CODE-AGENCY/Candidate-Lookup-by-CODE#7]
Ha keresés közben állítok be egy új platform sleection-t, akkor arra akkor még nem tudok rákerenis.

jó lenne, ha ez úgy mehetne, hogy

- jobb gomb
- options
- search settings
- kiválasztom a platformokat
- megjelenik a search gomb 
- és máris tudok eben a platform selection-ben keresni 
- 
![Screenshot 2022-09-12 at 10 38 27](https://user-images.githubusercontent.com/33448047/189610303-0462fafc-8323-4279-b0ad-a04c72104e31.png)

**Comment by GuBee33** [comment]
ha jól értem az a kérés hogy 1-el kevesebb gombnyomás legyen? (azaz ha megvan az új lista akkor egyből menjen a keresés és ne kelljen elmenti először és utána keresésre nyomni, hanem egyből menjen a keresés is?

**Comment by thebalazs** [comment]
az van, hogy most elmenti, de nem lehet használni a kereső gombját ugyanabban az ablakban. tehát most elmenti, becsukom az ablakot, újranyitom, és csak akkor működik a gomb. 

ezt kéne megcsinálni úgy, hogy megcsinálom, gomb a helyére kerül és máris klikkelhető legyen
